version: '3.8'

services:
  tms:
    container_name: tms_db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_db
      - postgres_user
      - postgres_password
    ports:
      - '5432:5432'
    volumes:
      - /var/opt/data/tms_db:/var/lib/postgresql/data
volumes:
  db:
    driver: local

secrets:
  postgres_user:
    file: secrets/postgres_user.txt
  postgres_password:
    file: secrets/postgres_password.txt
  postgres_db:
    file: secrets/postgres_db.txt