spring:
  application:
    name: ${APP_NAME}
  sql:
    init:
      data-locations: classpath:data.sql
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_DB}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
server:
  port: ${APP_PORT}

##JWT
security:
  jwt:
    secretKey: ${SECRET_KEY}
    expiresInMs: ${EXPIRES_IN_MS}

##OPEN API
springdoc:
  api-docs:
    path: "/api/v1/api-docs"
  swagger-ui:
    path: "/api/v1/swagger-ui"